### PR TITLE
Fixes #159 Disable negative values check for application source

### LINKED ISSUE #159: Disable negative values check for application source
Was already the case before - but does not work anymore due to moving applications under the Events node.

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

File: src/OSPSuite.SimModelNative/src/Species.cpp [hunk 1]
```diff
@@ -82,6 +82,7 @@ void Species::LoadFromXMLNode (const XMLNode & pNode)
 	if ((_containerPath.find("SalivaGland") != string::npos) ||
 		(_containerPath.find("IgG_Source") != string::npos) ||
 		(_containerPath.find("ParticleBin_") != string::npos)||
+		(_containerPath.find("|Events|") != string::npos) ||
 		(_containerPath.find("|Applications|") != string::npos))
```
Comment (Yuri05) [inline src/OSPSuite.SimModelNative/src/Species.cpp:86]: Ignoring all molecule amounts under the **Events** node when checking for negative values
(also keeping **Applications** in the exclusions list in order to run the simulations created with <V12)

File: tests/OSPSuite.SimModel.Tests/SimulationSpecs.cs [hunk 2]
```diff
@@ -481,6 +481,7 @@ public void should_load_finalize_and_run_simulation(string shortFileName)
 
       protected static IEnumerable<string> TestData()
       {
+         yield return "12.0_Brockmoller2005_CPA";
```
Comment (Yuri05) [inline tests/OSPSuite.SimModel.Tests/SimulationSpecs.cs:484]: one of the simulation from the HI qualification which produce negative values in V12

File: src/OSPSuite.SimModelNative/src/Species.cpp (hunk 1 above)
Comment (msevestre) [reply src/OSPSuite.SimModelNative/src/Species.cpp:86]: crazy

**Review by msevestre — APPROVED** [review]
