### PR TITLE
Fixes #139 Access violation

### LINKED ISSUE #139: Access violation
When trying to run the simulation attached: MoBi crashes completely without an error message (both MoBi 10 and 11)
[EntericCoatedTablet.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/files/8445044/EntericCoatedTablet.zip)

In the Windows event log there is the error below:
```
Application: MoBi.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OSPSuite.SimModel.SimulationImports.RunSimulation(IntPtr, Boolean ByRef, Double ByRef, Double ByRef, Boolean ByRef, System.String ByRef)
   at OSPSuite.SimModel.Simulation.RunSimulation()
   at OSPSuite.Core.Domain.Services.SimModelManager.simulate()
   at OSPSuite.Core.Domain.Services.SimModelManager.doIfNotCanceled(System.Action)
   at OSPSuite.Core.Domain.Services.SimModelManager.RunSimulation(OSPSuite.Core.Domain.IModelCoreSimulation, OSPSuite.Core.Domain.SimulationRunOptions)
   at MoBi.Presentation.Tasks.SimulationRunner.startSimulationRun(MoBi.Core.Domain.Model.IMoBiSimulation)
   at MoBi.Presentation.Tasks.SimulationRunner.RunSimulation(MoBi.Core.Domain.Model.IMoBiSimulation, Boolean)
   at MoBi.Presentation.UICommand.RunActiveSimulationCommandBase.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(OSPSuite.Presentation.MenuAndBars.IUICommand, OSPSuite.Utility.Events.IEventPublisher, OSPSuite.Core.Services.IChangePropagator)
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(OSPSuite.Presentation.MenuAndBars.IUICommand)
   at OSPSuite.Presentation.MenuAndBars.MenuBarButton.Click()
   at OSPSuite.UI.Mappers.MenuBarButtonToBarItemMapperBase+<>c__DisplayClass1_0.<UpdateBarButtonItem>b__0(System.Object, DevExpress.XtraBars.ItemClickEventArgs)
   at DevExpress.XtraBars.BarItem.OnClick(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.BarButtonItem.OnClick(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(DevExpress.XtraBars.BarLinkAction, System.Object)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPressItem(DevExpress.Utils.DXMouseEventArgs, DevExpress.XtraBars.Ribbon.ViewInfo.RibbonHitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnMouseUp(DevExpress.Utils.DXMouseEventArgs)
   at DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnMouseUp(DevExpress.Utils.DXMouseEventArgs)
   at DevExpress.XtraBars.Ribbon.RibbonControl.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(System.Windows.Forms.Message ByRef)
   at DevExpress.XtraBars.Ribbon.RibbonControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at DevExpress.Utils.Drawing.Helpers.NativeMethods+UnsafeNativeMethods.DefSubclassProc(IntPtr, IntPtr, IntPtr, IntPtr)
   at DevExpress.Utils.Drawing.Helpers.Win32SubclasserFactory+Win32Subclasser.SubClassProcInner(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at MoBi.UI.Services.MoBiApplication.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   at MoBi.Program.Main(System.String[])

```

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

File: src/OSPSuite.SimModelNative/src/TableFormulaWithOffset.cpp [hunk 1]
```diff
@@ -155,7 +155,9 @@ void TableFormulaWithOffset::Finalize()
 
 vector <double> TableFormulaWithOffset::RestartTimePoints()
 {
-	assert ((_tableObject != NULL) && (_offsetObject != NULL));
+	//table formula can be NULL if the original table formula was constant and thus was replaced by its value
+	if (_tableFormula == NULL)
+		return vector<double>();
```
Comment (Yuri05) [inline src/OSPSuite.SimModelNative/src/TableFormulaWithOffset.cpp:160]: in the original example, the table formulation was constantly zero; the table formula was replaced early in the process with its const value (zero) and the old line 172 below crashed then

**Review by abdelr — APPROVED** [review]
